name: 👋 Test issue template
description: This is a test issue template
labels:
  - need help

body:
  - type: markdown
    attributes:
      value: |
        Testing!!!

  - type: checkboxes
    id: test_checkbox
    attributes:
      label: Test Checkbox
      description: This is a testing checkbox
      options:
        - label: This is a label
          required: true